spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/real-estate
    username: postgres
    password: postgres
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 10
    filters: stat
  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  jackson:
    serialization:
      INDENT_OUTPUT: true

app-config:
  source:
    directory: ${DIRECTORY_DATA_TRAIN:image-store/}
jwt:
  secret: JWTSuperSecretKey
server:
  port: 8082
  servlet:
    context-path: /api